
por ahora para poder ejecutar la prueba es de manera local, aplicando los siguentes comandos

python3 manage.py runserver